# Generated by Django 4.0.3 on 2022-03-30 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customer_profile_pic_alter_customer_user_and_more'),
    ]



