# Generated by Django 4.0.3 on 2022-03-30 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_client_alter_dudes_id_alter_stuff_id_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuff',
            name='client',
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.client'),
        ),
        migrations.DeleteModel(
            name='Dudes',
        ),
        migrations.DeleteModel(
            name='Stuff',
        ),
    ]
