# Generated by Django 4.0.3 on 2022-04-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_stuff_client_alter_contract_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_num',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='annual_payments',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='calc_method',
            field=models.CharField(choices=[('Declining Balance', 'Declining Balance'), ('Fixed Flat', 'Fixed Flat')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='interest_rate',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='months',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='loan',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
