# Generated by Django 4.0.3 on 2022-04-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_client_balance_client_phone_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='balance',
        ),
        migrations.AlterField(
            model_name='contract',
            name='interest_rate',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], default='Active', max_length=200, null=True),
        ),
    ]
