# Generated by Django 4.0.3 on 2022-04-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_contract_client_alter_payment_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_paid',
            field=models.DateField(blank=True, null=True),
        ),
    ]
