# Generated by Django 4.0.3 on 2022-04-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_contract_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='product',
            field=models.CharField(choices=[('Special', 'Special'), ('Classic', 'Classic'), ('Imobil', 'Imobil')], default='Classic', max_length=200, null=True),
        ),
    ]
