# Generated by Django 4.0.3 on 2022-04-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_contract_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='interest_paid',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='penalties_paid',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='principal_paid',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.CharField(choices=[('Special', 'Special'), ('Imobil', 'Imobil'), ('Classic', 'Classic')], default='Classic', max_length=200, null=True),
        ),
    ]
