# Generated by Django 4.0.3 on 2022-04-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_payment_interest_paid_payment_penalties_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='advance',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.CharField(choices=[('Classic', 'Classic'), ('Special', 'Special'), ('Imobil', 'Imobil')], default='Classic', max_length=200, null=True),
        ),
    ]
