# Generated by Django 4.0.3 on 2022-05-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_contract_month_sum_alter_contract_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='grace_period',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.CharField(choices=[('Classic', 'Classic'), ('Imobil', 'Imobil'), ('Special', 'Special')], default='Classic', max_length=200, null=True),
        ),
    ]
