# Generated by Django 4.0.3 on 2022-05-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_contract_id_alter_contract_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.CharField(choices=[('Imobil', 'Imobil'), ('Classic', 'Classic'), ('Special', 'Special')], default='Classic', max_length=200, null=True),
        ),
    ]
