# Generated by Django 4.0.3 on 2022-05-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_contract_product_waive'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Waive',
            new_name='PenaltyWaive',
        ),
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.CharField(choices=[('Special', 'Special'), ('Classic', 'Classic'), ('Imobil', 'Imobil')], default='Classic', max_length=200, null=True),
        ),
    ]
