# Generated by Django 4.0.3 on 2022-05-31 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_rename_waive_penaltywaive_alter_contract_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.CharField(choices=[('Imobil', 'Imobil'), ('Classic', 'Classic'), ('Special', 'Special')], default='Classic', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='InterestWaive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(null=True)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.contract')),
            ],
        ),
    ]
