# Generated by Django 4.0.5 on 2022-06-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_contract_product_interestwaive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.CharField(choices=[('Classic', 'Classic'), ('Imobil', 'Imobil'), ('Special', 'Special')], default='Classic', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Colectare', 'Colectare'), ('Judecata', 'Judecata')], default='Active', max_length=200, null=True),
        ),
    ]
