# Generated by Django 4.0.5 on 2022-06-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_contract_product_alter_contract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bank_account',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='bank_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='bank_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='idnp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='scope',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.CharField(choices=[('Special', 'Special'), ('Classic', 'Classic'), ('Imobil', 'Imobil')], default='Classic', max_length=200, null=True),
        ),
    ]
