# Generated by Django 4.0.5 on 2022-06-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_client_bank_account_client_bank_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fidejusor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('phone_num', models.CharField(max_length=20, null=True)),
                ('idnp', models.IntegerField(null=True)),
                ('id_card_nr', models.CharField(max_length=200, null=True)),
                ('id_card_office', models.CharField(max_length=200, null=True)),
                ('id_card_date', models.CharField(max_length=200, null=True)),
                ('birth_date', models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='id_card_date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='id_card_nr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='id_card_office',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.CharField(choices=[('Classic', 'Classic'), ('Imobil', 'Imobil'), ('Special', 'Special')], default='Classic', max_length=200, null=True),
        ),
    ]
