# Generated by Django 4.0.4 on 2022-06-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_fidejusor_client_id_card_date_client_id_card_nr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.CharField(choices=[('Imobil', 'Imobil'), ('Classic', 'Classic'), ('Special', 'Special')], default='Classic', max_length=200, null=True),
        ),
    ]
