# Generated by Django 4.0.4 on 2022-06-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_alter_client_bank_account_alter_client_bank_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_card_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.CharField(choices=[('Classic', 'Classic'), ('Imobil', 'Imobil'), ('Special', 'Special')], default='Classic', max_length=200, null=True),
        ),
    ]
