# Generated by Django 4.0.4 on 2022-06-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_client_id_card_date_alter_contract_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_num',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.CharField(choices=[('Classic', 'Classic'), ('Special', 'Special'), ('Imobil', 'Imobil')], default='Classic', max_length=200, null=True),
        ),
    ]
