# Generated by Django 4.0.4 on 2022-06-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_alter_client_phone_num_alter_contract_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='calc_method',
            field=models.CharField(choices=[('Declining Balance', 'Declining Balance'), ('Declining Balance (OLD)', 'Declining Balance (OLD)'), ('Fixed Flat', 'Fixed Flat')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.CharField(choices=[('Imobil', 'Imobil'), ('Classic', 'Classic'), ('Special', 'Special')], default='Classic', max_length=200, null=True),
        ),
    ]
