# Generated by Django 4.0.4 on 2022-06-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_alter_contract_calc_method_alter_contract_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='scope',
        ),
        migrations.AddField(
            model_name='contract',
            name='scope',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.CharField(choices=[('Imobil', 'Imobil'), ('Special', 'Special'), ('Classic', 'Classic')], default='Classic', max_length=200, null=True),
        ),
    ]
