# Generated by Django 4.0.4 on 2022-07-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_remove_client_scope_contract_scope_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='advance',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='interest_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='penalties_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='principal_paid',
        ),
        migrations.AddField(
            model_name='contract',
            name='currency',
            field=models.CharField(choices=[('MDL', 'MDL'), ('EUR', 'EUR')], default='MDL', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.CharField(choices=[('Classic', 'Classic'), ('Special', 'Special'), ('Imobil', 'Imobil')], default='Classic', max_length=200, null=True),
        ),
    ]
