# Generated by Django 4.0.4 on 2022-07-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_remove_payment_advance_remove_payment_interest_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.CharField(choices=[('Special', 'Special'), ('Classic', 'Classic'), ('Imobil', 'Imobil')], default='Classic', max_length=200, null=True),
        ),
    ]
