# Generated by Django 4.0.4 on 2022-07-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_alter_contract_currency_alter_contract_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.CharField(choices=[('Classic', 'Classic'), ('Imobil', 'Imobil'), ('Special', 'Special')], default='Classic', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
        ),
    ]
