# Generated by Django 4.0.4 on 2022-07-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_alter_contract_product_alter_payment_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=15),
        ),
    ]
