# Generated by Django 4.0.4 on 2022-07-22 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_alter_payment_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='fidejusor',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.contract'),
        ),
        migrations.AddField(
            model_name='fidejusor',
            name='num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='currency',
            field=models.CharField(choices=[('MDL', 'MDL'), ('EUR', 'EUR')], default='MDL', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=15),
        ),
    ]
