# Generated by Django 4.0.4 on 2022-07-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_fidejusor_contract_fidejusor_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prognosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='person',
            field=models.CharField(choices=[('Physical', 'Physical'), ('Juridical', 'Juridical')], default='Physical', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='sector',
            field=models.CharField(choices=[('Agricultură', 'Agricultură'), ('Industria Alim. și Procesare', 'Industria Alim. și Procesare'), ('Imobil', 'Imobil'), ('Comerț', 'Comerț'), ('Prestarea serviciilor', 'Prestarea serviciilor'), ('Consum', 'Consum'), ('Alte scopuri', 'Alte scopuri')], default='Agricultură', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='term',
            field=models.CharField(choices=[('Long', 'Long'), ('Short', 'Short')], default='Long', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('MDL', 'MDL')], default='MDL', max_length=100, null=True),
        ),
    ]
