# Generated by Django 4.0.4 on 2022-07-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_prognosis_client_gender_client_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='idnp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='currency',
            field=models.CharField(choices=[('MDL', 'MDL'), ('EUR', 'EUR')], default='MDL', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.CharField(choices=[('Imobil', 'Imobil'), ('Special', 'Special'), ('Classic', 'Classic')], default='Classic', max_length=200, null=True),
        ),
    ]
