# Generated by Django 4.0.4 on 2022-08-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_alter_client_idnp_alter_contract_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='idnp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.CharField(choices=[('Consum', 'Consum'), ('Special', 'Special'), ('Classic', 'Classic'), ('Imobil', 'Imobil')], default='Classic', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Colectare', 'Colectare'), ('Judecata', 'Judecata'), ('Bad Client', 'Bad Client')], default='Active', max_length=200, null=True),
        ),
    ]
