# Generated by Django 4.0.4 on 2022-10-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_contract_exchange_rate_alter_client_idnp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('MDL', 'MDL')], default='MDL', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_paid',
            field=models.DateField(null=True),
        ),
    ]
