# Generated by Django 4.0.4 on 2022-10-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_alter_contract_currency_alter_payment_date_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrears',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.CharField(choices=[('Consum', 'Consum'), ('Special', 'Special'), ('Imobil', 'Imobil'), ('Classic', 'Classic')], default='Classic', max_length=200, null=True),
        ),
    ]
