# Generated by Django 4.0.4 on 2024-01-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_arrears_alter_contract_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrears',
            name='person',
            field=models.CharField(choices=[('Physical', 'Physical'), ('Juridical', 'Juridical')], default='All', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='date_closed',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.CharField(choices=[('Special', 'Special'), ('Consum', 'Consum'), ('Classic', 'Classic'), ('Imobil', 'Imobil')], default='Classic', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Colectare', 'Colectare'), ('Judecata', 'Judecata'), ('Bad Client', 'Bad Client'), ('Refinantare', 'Refinantare')], default='Active', max_length=200, null=True),
        ),
    ]
