# Generated by Django 4.0.4 on 2024-01-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_arrears_person_contract_date_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='currency',
            field=models.CharField(choices=[('MDL', 'MDL'), ('EUR', 'EUR')], default='MDL', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.CharField(choices=[('Imobil', 'Imobil'), ('Special', 'Special'), ('Consum', 'Consum'), ('Classic', 'Classic')], default='Classic', max_length=200, null=True),
        ),
    ]
