# Generated by Django 4.0.4 on 2024-11-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_contract_comments_alter_contract_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='idnp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_closed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.CharField(choices=[('Special', 'Special'), ('Consum', 'Consum'), ('Imobil', 'Imobil'), ('Classic', 'Classic')], default='Classic', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sector',
            field=models.CharField(choices=[('Agricultură', 'Agricultură'), ('Comerț', 'Comerț'), ('Construcții', 'Construcții'), ('Consum', 'Consum'), ('Imobil', 'Imobil'), ('Transport', 'Transport'), ('Prestarea serviciilor', 'Prestarea serviciilor'), ('Industria energetică', 'Industria energetică'), ('Industria productivă', 'Industria productivă'), ('Industria Alim. și Procesare', 'Industria Alim. și Procesare'), ('Alte scopuri', 'Alte scopuri')], default='Agricultură', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fidejusor',
            name='idnp',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
