# Generated by Django 4.0.10 on 2025-01-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_alter_client_idnp_alter_contract_date_closed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('MDL', 'MDL')], default='MDL', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.CharField(choices=[('Consum', 'Consum'), ('Imobil', 'Imobil'), ('Special', 'Special'), ('Classic', 'Classic')], default='Classic', max_length=200, null=True),
        ),
    ]
