# Generated by Django 4.0.10 on 2025-01-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_client_administrator_client_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='currency',
            field=models.CharField(choices=[('MDL', 'MDL'), ('EUR', 'EUR')], default='MDL', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.CharField(choices=[('Special', 'Special'), ('Consum', 'Consum'), ('Imobil', 'Imobil'), ('Classic', 'Classic')], default='Classic', max_length=200, null=True),
        ),
    ]
