# Generated by Django 4.0.10 on 2025-01-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_alter_contract_currency_alter_contract_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('MDL', 'MDL')], default='MDL', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.CharField(choices=[('Classic', 'Classic'), ('Special', 'Special'), ('Consum', 'Consum'), ('Imobil', 'Imobil')], default='Classic', max_length=200, null=True),
        ),
    ]
