# Generated by Django 4.0.10 on 2026-05-10 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_contract_comission_alter_contract_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.CharField(choices=[('Imobil', 'Imobil'), ('Special', 'Special'), (
                'Consum', 'Consum'), ('Classic', 'Classic')], default='Classic', max_length=200, null=True),
        ),
        '''
        migrations.CreateModel(
            name='Gajist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(null=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('idnp', models.CharField(max_length=20, null=True)),
                ('domiciliul', models.CharField(max_length=200, null=True)),
                ('marca', models.CharField(max_length=200, null=True)),
                ('model', models.CharField(max_length=200, null=True)),
                ('nr_de_inmatriculare', models.CharField(max_length=200, null=True)),
                ('anul_fabricatiei', models.CharField(max_length=200, null=True)),
                ('nr_caroserie', models.CharField(max_length=200, null=True)),
                ('culoare', models.CharField(max_length=200, null=True)),
                ('seria_certificat', models.CharField(max_length=200, null=True)),
                ('nr_certificat', models.CharField(max_length=200, null=True)),
                ('data_emiterii_certificat', models.CharField(max_length=200, null=True)),
                ('valoarea_de_gaj', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('phone_num', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=20, null=True)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.contract')),
            ],
        ),
    '''
    ]
