# Generated by Django 4.0.10 on 2026-06-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_alter_contract_product_gajist'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='fee_issue',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='fee_issue_months',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='residual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('MDL', 'MDL')], default='MDL', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.CharField(choices=[('Special', 'Special'), ('Consum', 'Consum'), ('Classic', 'Classic'), ('Imobil', 'Imobil')], default='Classic', max_length=200, null=True),
        ),
    ]
