# Generated by Django 4.0.10 on 2026-06-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_contract_fee_issue_contract_fee_issue_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='penalty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='currency',
            field=models.CharField(choices=[('MDL', 'MDL'), ('EUR', 'EUR')], default='MDL', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.CharField(choices=[('Consum', 'Consum'), ('Imobil', 'Imobil'), ('Classic', 'Classic'), ('Special', 'Special')], default='Classic', max_length=200, null=True),
        ),
    ]
